const Carousel = require('../models/Carousel');
const multer = require('multer');
const streamifier = require('streamifier');
const cloudinary = require('../config/cloudinary'); // Uses your verified working config!

// 1. 🚀 Use memoryStorage exactly like your Projects route does!
const storage = multer.memoryStorage();
const upload = multer({ storage: storage }).single('image');
exports.uploadMiddleware = upload;

// ⚡ Helper: Cloudinary Upload Stream (Wrapped in a Promise to prevent Vercel 504 timeouts)
const uploadToCloudinary = (fileBuffer) => {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder: 'hero_carousels' },
      (error, result) => {
        if (result) {
          resolve(result);
        } else {
          reject(error);
        }
      }
    );
    streamifier.createReadStream(fileBuffer).pipe(stream);
  });
};

// 2. Fetch public slides context list
exports.getSlides = async (req, res) => {
  try {
    const slides = await Carousel.find().sort({ order: 1 });
    res.status(200).json(slides);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// 3. Create and commit verified slide configurations
exports.createSlide = async (req, res) => {
  try {
    // 🛡️ ROLE GATE: Check if the decoded token user is a super_admin
    if (!req.admin || req.admin.role !== 'super_admin') {
      return res.status(403).json({ message: 'Access Denied: Super Admin authorization credentials required.' });
    }

    if (!req.file) {
      return res.status(400).json({ message: 'Image file attachment is required.' });
    }
    
    // Read 'tagline' and 'order' from request body
    const { tagline, order } = req.body;
    const requestedOrder = (order !== undefined && order !== null && order !== '') ? Number(order) : 0;

    // 🚨 NEW DUPLICATE CHECK: Make sure the order number isn't taken!
    const existingSlide = await Carousel.findOne({ order: requestedOrder });
    if (existingSlide) {
      return res.status(400).json({ 
        message: `A slide with index ${requestedOrder} already exists. Please choose a different number.` 
      });
    }

    // 🚀 Execute the Cloudinary stream upload ONLY if the index is available
    const cloudinaryResult = await uploadToCloudinary(req.file.buffer);
    
    const newSlide = new Carousel({
      image: {
        url: cloudinaryResult.secure_url,     // The secure link generated by Cloudinary
        public_id: cloudinaryResult.public_id // The public asset tracker id
      },
      tagline : tagline || '',
      order: requestedOrder
    });

    await newSlide.save();
    res.status(201).json(newSlide);
  } catch (error) {
    console.error("Carousel Upload Error:", error);
    
    // 🚨 FIX: Catch MongoDB's native duplicate key error!
    if (error.code === 11000) {
      return res.status(400).json({ 
        message: "This position number is already taken! Please choose a different order number." 
      });
    }

    res.status(500).json({ message: error.message });
  }
};
// 4. Purge target data segments across Cloudinary and MongoDB
exports.deleteSlide = async (req, res) => {
  try {
    // 🛡️ ROLE GATE: Check if the decoded token user is a super_admin
    if (!req.admin || req.admin.role !== 'super_admin') {
      return res.status(403).json({ message: 'Access Denied: Super Admin authorization credentials required.' });
    }

    const slide = await Carousel.findById(req.params.id);
    if (!slide) {
      return res.status(404).json({ message: 'Target slide asset details not found.' });
    }

    // Erase the photo asset from Cloudinary
    if (slide.image?.public_id) {
      await cloudinary.uploader.destroy(slide.image.public_id);
    }

    await slide.deleteOne();
    res.status(200).json({ message: 'Slide purged successfully across infrastructure layers.' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};