const Carousel = require('../models/Carousel');
const cloudinary = require('cloudinary').v2;
const multer = require('multer');
const { CloudinaryStorage } = require('multer-storage-cloudinary');

// 1. Configure Cloudinary Storage Staging Parameters
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: 'hero_carousels',
    allowed_formats: ['jpg', 'jpeg', 'png', 'webp'],
  },
});

// Configure upload interceptor middleware
const upload = multer({ storage: storage }).single('image');
exports.uploadMiddleware = upload;

// 2. Fetch public slides context list (Anyone can view)
exports.getSlides = async (req, res) => {
  try {
    const slides = await Carousel.find().sort({ order: 1 });
    res.status(200).json(slides);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// 3. Create and commit verified slide configurations (STRICTLY SUPER ADMIN)
exports.createSlide = async (req, res) => {
  try {
    // 🛡️ ROLE GATE: Check if the decoded token user is a super_admin
    if (!req.admin || req.admin.role !== 'super_admin') {
      return res.status(403).json({ message: 'Access Denied: Super Admin authorization credentials required.' });
    }

    // Check if multer processed the incoming image file successfully
    if (!req.file) {
      return res.status(400).json({ message: 'Image file attachment is required.' });
    }
    
    // Read 'tagline' from request body
    const { tagline, order } = req.body;
    
    
    const newSlide = new Carousel({
      image: {
        url: req.file.path,             // The secure link generated by Cloudinary
        public_id: req.file.filename    // The public asset tracker id
      },
      tagline : tagline || '', // Optional tagline, default to empty string if not provided
      order: order ? Number(order) : 0
    });

    await newSlide.save();
    res.status(201).json(newSlide);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// 4. Purge target data segments across Cloudinary and MongoDB (STRICTLY SUPER ADMIN)
exports.deleteSlide = async (req, res) => {
  try {
    // 🛡️ ROLE GATE: Check if the decoded token user is a super_admin
    if (!req.admin || req.admin.role !== 'super_admin') {
      return res.status(403).json({ message: 'Access Denied: Super Admin authorization credentials required.' });
    }

    const slide = await Carousel.findById(req.params.id);
    if (!slide) {
      return res.status(404).json({ message: 'Target slide asset details not found.' });
    }

    // Erase the photo asset folder tracking index from Cloudinary
    if (slide.image?.public_id) {
      await cloudinary.uploader.destroy(slide.image.public_id);
    }

    await slide.deleteOne();
    res.status(200).json({ message: 'Slide purged successfully across infrastructure layers.' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};